/* Supervised capability RFC pipeline. It never edits production or elevates its own permissions. */
const crypto = require('crypto');
const store = require('./persistence');
const observability = require('./observability');

const FILE = 'evolution-rfcs.json';
const PROTECTED_DOMAINS = ['auth', 'secrets', 'billing', 'entitlements', 'policy', 'permissions', 'observability', 'evolution', 'rollback', 'financial', 'destructive'];
const STATES = ['GAP', 'RFC', 'LAB', 'SANDBOXED', 'TESTED', 'SECURITY_REVIEW', 'CANARY_READY', 'APPROVED', 'RELEASED', 'REJECTED', 'ROLLED_BACK'];
const TRANSITIONS = {
    GAP:['RFC','REJECTED'], RFC:['LAB','REJECTED'], LAB:['SANDBOXED','REJECTED'], SANDBOXED:['TESTED','REJECTED'],
    TESTED:['SECURITY_REVIEW','LAB','REJECTED'], SECURITY_REVIEW:['CANARY_READY','LAB','REJECTED'], CANARY_READY:['APPROVED','REJECTED'],
    APPROVED:['RELEASED','REJECTED'], RELEASED:['ROLLED_BACK'], REJECTED:[], ROLLED_BACK:[]
};

function load(){const d=store.loadJson(FILE,{rfcs:[],savedAt:null});d.rfcs=Array.isArray(d.rfcs)?d.rfcs:[];return d;}function save(d){d.savedAt=new Date().toISOString();store.saveJson(FILE,d);}
function propose(input={},actor='admin',traceId){const title=clean(input.title,180),description=clean(input.description,1600),domain=clean(input.domain,80).toLowerCase();if(title.length<3||description.length<10)return{ok:false,error:'evolution_rfc_invalid'};if(PROTECTED_DOMAINS.some(item=>domain.includes(item)))return{ok:false,error:'protected_domain_not_modifiable'};const d=load(),now=new Date().toISOString();const rfc={id:`rfc_${Date.now().toString(36)}_${crypto.randomBytes(5).toString('hex')}`,title,description,domain,detectedGap:clean(input.detectedGap,600),acceptanceCriteria:unique(input.acceptanceCriteria,30,300),risk:clean(input.risk||'medium',20),state:'GAP',branch:null,testEvidence:[],securityEvidence:[],canaryMetrics:null,createdAt:now,updatedAt:now,createdBy:String(actor),history:[{state:'GAP',at:now,actor:String(actor)}]};d.rfcs.push(rfc);save(d);audit(traceId,'evolution.proposed',rfc);return{ok:true,rfc};}
function transition(id,nextState,input={},actor='admin',traceId){const d=load(),r=d.rfcs.find(x=>x.id===id);if(!r)return{ok:false,error:'evolution_rfc_not_found'};if(!(TRANSITIONS[r.state]||[]).includes(nextState))return{ok:false,error:'evolution_transition_invalid',from:r.state,to:nextState};if(['TESTED','SECURITY_REVIEW','CANARY_READY','APPROVED','RELEASED'].includes(nextState)&&!input.evidence)return{ok:false,error:'evolution_evidence_required'};if(nextState==='LAB'&&!/^codex\//.test(String(input.branch||'')))return{ok:false,error:'sandbox_branch_required'};if(input.branch)r.branch=clean(input.branch,160);if(input.evidence){const entry={...safeObject(input.evidence),at:new Date().toISOString(),actor:String(actor)};(nextState==='SECURITY_REVIEW'?r.securityEvidence:r.testEvidence).push(entry);}if(input.canaryMetrics)r.canaryMetrics=safeObject(input.canaryMetrics);r.state=nextState;r.updatedAt=new Date().toISOString();r.history.push({state:nextState,at:r.updatedAt,actor:String(actor),reason:clean(input.reason,240)||null});save(d);audit(traceId,'evolution.transition',r);return{ok:true,rfc:r};}
function list(input={}){let items=load().rfcs;if(input.state)items=items.filter(x=>x.state===input.state);return items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,Math.max(1,Math.min(Number(input.limit)||100,500)));}function stats(){const items=load().rfcs;return{total:items.length,byState:items.reduce((a,i)=>(a[i.state]=(a[i.state]||0)+1,a),{})};}
function audit(traceId,type,rfc){observability.record({trace_id:traceId,severity:'INFO',service:'evolution',event_type:type,action:rfc.id,status:rfc.state,metadata_redacted:{domain:rfc.domain,branch:rfc.branch}});}function clean(v,m){return String(v||'').trim().replace(/[\u0000-\u001f]/g,'').slice(0,m);}function unique(v,max,len){return[...new Set((Array.isArray(v)?v:[]).map(x=>clean(x,len)).filter(Boolean))].slice(0,max);}function safeObject(v){if(!v||typeof v!=='object'||Array.isArray(v))return{};const s=JSON.stringify(v);return JSON.parse(s.length>65536?'{}':s);}
module.exports={PROTECTED_DOMAINS,STATES,TRANSITIONS,propose,transition,list,stats,_load:load};
