/* Persistent missions and supervised procedure learning. */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const userStore = require('../user-store');
const observability = require('./observability');
const persistence = require('./persistence');

const MISSION_STATES = ['DRAFT', 'ACTIVE', 'PAUSED', 'BLOCKED', 'COMPLETED', 'CANCELLED'];
const PROCEDURE_STATES = ['DRAFT', 'OBSERVED', 'SIMULATED', 'APPROVED', 'ASSISTED', 'TRUSTED', 'RETIRED'];
const PROCEDURE_TRANSITIONS = { DRAFT:['OBSERVED','RETIRED'], OBSERVED:['SIMULATED','DRAFT','RETIRED'], SIMULATED:['APPROVED','DRAFT','RETIRED'], APPROVED:['ASSISTED','RETIRED'], ASSISTED:['TRUSTED','APPROVED','RETIRED'], TRUSTED:['ASSISTED','RETIRED'], RETIRED:[] };

function fileFor(userId) { return path.join(userStore.userDir(userId), 'missions-procedures.json'); }
function load(userId) { try { const file=fileFor(userId); if(!fs.existsSync(file)) return {missions:[],procedures:[]}; const data=JSON.parse(fs.readFileSync(file,'utf8')); data.missions=Array.isArray(data.missions)?data.missions:[]; data.procedures=Array.isArray(data.procedures)?data.procedures:[]; return data; } catch { return {missions:[],procedures:[]}; } }
function save(userId,data){const file=fileFor(userId),temp=path.join(path.dirname(file),`.missions-${process.pid}-${Date.now()}.tmp`);data.savedAt=new Date().toISOString();fs.writeFileSync(temp,JSON.stringify(data,null,2),{encoding:'utf8',mode:0o600});try{fs.renameSync(temp,file);}catch{fs.copyFileSync(temp,file);fs.unlinkSync(temp);}}

function createMission(userId,input={},traceId){
    const objective=clean(input.objective,500); const criteria=unique(input.successCriteria,30,300);
    if(objective.length<3)return{ok:false,error:'mission_objective_required'};
    if(!criteria.length)return{ok:false,error:'mission_success_criteria_required'};
    const data=load(userId),now=new Date().toISOString();
    const mission={id:`mission_${Date.now().toString(36)}_${crypto.randomBytes(5).toString('hex')}`,objective,successCriteria:criteria,deadline:dateOrNull(input.deadline),owner:clean(input.owner||'user',100),subgoals:normalizeItems(input.subgoals),blockers:normalizeItems(input.blockers),commitments:normalizeItems(input.commitments),nextActions:normalizeItems(input.nextActions),confidence:confidence(input.confidence),status:'DRAFT',entitlementScope:unique(input.entitlementScope,30,100),autonomyScope:clean(input.autonomyScope||'L2',2),budgetScope:safeObject(input.budgetScope),createdAt:now,updatedAt:now,completedAt:null};
    data.missions.push(mission);save(userId,data);audit(userId,traceId,'mission.created',mission.id,mission.status);return{ok:true,mission};
}
function updateMission(userId,id,input={},traceId){const data=load(userId),m=data.missions.find(item=>item.id===id);if(!m)return{ok:false,error:'mission_not_found'};if(input.status&&!MISSION_STATES.includes(input.status))return{ok:false,error:'mission_state_invalid'};for(const field of ['subgoals','blockers','commitments','nextActions'])if(input[field])m[field]=normalizeItems(input[field]);if(input.status)m.status=input.status;if(input.confidence!==undefined)m.confidence=confidence(input.confidence);m.updatedAt=new Date().toISOString();if(m.status==='COMPLETED')m.completedAt=m.updatedAt;save(userId,data);audit(userId,traceId,'mission.updated',m.id,m.status);return{ok:true,mission:m};}
function listMissions(userId,input={}){let items=load(userId).missions;if(input.status)items=items.filter(item=>item.status===input.status);return items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,Math.max(1,Math.min(Number(input.limit)||100,500)));}

function createProcedure(userId,input={},traceId){const name=clean(input.name,160),steps=normalizeSteps(input.steps);if(name.length<2)return{ok:false,error:'procedure_name_required'};if(!steps.length)return{ok:false,error:'procedure_steps_required'};const data=load(userId),now=new Date().toISOString();const procedure={id:`proc_${Date.now().toString(36)}_${crypto.randomBytes(5).toString('hex')}`,name,version:1,state:'DRAFT',consent:input.consent===true,captureMode:['web_observation','semantic_template','native_observation'].includes(input.captureMode)?input.captureMode:'web_observation',steps,inputs:unique(input.inputs,30,120),outputs:unique(input.outputs,30,120),supportedNodes:unique(input.supportedNodes,10,20).filter(item=>['WEB','DESKTOP','ANDROID','IOS'].includes(item)),requiredSkills:unique(input.requiredSkills,50,120),evidence:[],successRate:null,createdAt:now,updatedAt:now};data.procedures.push(procedure);save(userId,data);audit(userId,traceId,'procedure.created',procedure.id,procedure.state);return{ok:true,procedure};}
function transitionProcedure(userId,id,nextState,input={},traceId){const data=load(userId),p=data.procedures.find(item=>item.id===id);if(!p)return{ok:false,error:'procedure_not_found'};if(!(PROCEDURE_TRANSITIONS[p.state]||[]).includes(nextState))return{ok:false,error:'procedure_transition_invalid',from:p.state,to:nextState};if(nextState==='OBSERVED'&&!p.consent)return{ok:false,error:'procedure_consent_required'};if(['SIMULATED','APPROVED','ASSISTED','TRUSTED'].includes(nextState)&&!input.evidence)return{ok:false,error:'procedure_evidence_required'};if(input.evidence)p.evidence.push({...safeObject(input.evidence),at:new Date().toISOString()});p.state=nextState;p.updatedAt=new Date().toISOString();if(input.successRate!==undefined)p.successRate=confidence(input.successRate);if(nextState==='DRAFT')p.version+=1;save(userId,data);audit(userId,traceId,'procedure.transition',p.id,p.state);return{ok:true,procedure:p};}
function listProcedures(userId,input={}){let items=load(userId).procedures;if(input.state)items=items.filter(item=>item.state===input.state);return items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,Math.max(1,Math.min(Number(input.limit)||100,500)));}
function stats(userId){const data=load(userId);return{missions:{total:data.missions.length,byState:countBy(data.missions,'status')},procedures:{total:data.procedures.length,byState:countBy(data.procedures,'state')}};}

function audit(userId,traceId,type,id,status){observability.record({trace_id:traceId,severity:'INFO',service:'missions',event_type:type,action:id,status,user_id_hash:persistence.hash(userId).slice(0,16)});}
function normalizeItems(value){return(Array.isArray(value)?value:[]).slice(0,100).map(item=>typeof item==='string'?{title:clean(item,240),status:'pending'}:{title:clean(item.title,240),status:clean(item.status||'pending',30),owner:clean(item.owner,100)||null,dueAt:dateOrNull(item.dueAt)}).filter(item=>item.title);}
function normalizeSteps(value){return(Array.isArray(value)?value:[]).slice(0,100).map((raw,index)=>{const step=typeof raw==='string'?{action:raw}:safeObject(raw);const risk=['read','local_write','external_write'].includes(step.risk)?step.risk:'read';return{order:index+1,action:clean(step.action,300),kind:['click','navigate','input','wait_visible','file.choose','file.latest_download','social.publish','social.send','ui.inspect','ui.focus','ui.click','ui.type','ui.wait','ui.scroll','ui.hotkey','ui.select_file','media.control','app.open'].includes(step.kind)?step.kind:'click',skill:clean(step.skill,120)||null,nodeType:['WEB','DESKTOP','ANDROID','IOS'].includes(step.nodeType)?step.nodeType:'WEB',route:clean(step.route,300)||null,target:normalizeTarget(step.target),payloadTemplate:safeTemplate(step.payloadTemplate),risk,requiresConfirmation:risk==='external_write'||step.requiresConfirmation===true,verify:step.verify!==false};}).filter(step=>step.action);}
function normalizeTarget(value){const target=safeObject(value),allowed={};for(const [key,max] of Object.entries({actionId:160,elementId:160,role:40,name:180,testId:160,app:100,window:180,screen:120,provider:40,automationId:180,controlType:60}))if(target[key])allowed[key]=clean(target[key],max);return allowed;}
function safeTemplate(value){const input=safeObject(value),out={};for(const [key,val] of Object.entries(input)){if(/password|passcode|token|secret|cookie|authorization|api.?key/i.test(key))continue;if(typeof val==='string')out[key]=clean(val,500);else if(typeof val==='number'||typeof val==='boolean'||val===null)out[key]=val;}return out;}
function unique(value,max,length){return[...new Set((Array.isArray(value)?value:[]).map(item=>clean(item,length)).filter(Boolean))].slice(0,max);}
function clean(value,max){return String(value||'').trim().replace(/[\u0000-\u001f]/g,'').slice(0,max);}function confidence(v){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(n,1)):.5;}function dateOrNull(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString();}function safeObject(v){if(!v||typeof v!=='object'||Array.isArray(v))return{};const s=JSON.stringify(v);return JSON.parse(s.length>32768?'{}':s);}function countBy(items,key){return items.reduce((a,i)=>(a[i[key]]=(a[i[key]]||0)+1,a),{});}
module.exports={MISSION_STATES,PROCEDURE_STATES,PROCEDURE_TRANSITIONS,createMission,updateMission,listMissions,createProcedure,transitionProcedure,listProcedures,stats,_load:load};
